// Maps a raw Open Plaques `primary_role_name` (e.g. "Prime Minister of Israel",
// "Nuclear physicist", "Portrait painter") onto a small set of broad occupation
// categories (e.g. "Politician", "Scientist", "Artist"). The raw role field has
// a very long tail (~850 distinct values), so the tracker's "By profession"
// breakdown is unreadable without generalising. See docs/API_SPEC.md.
//
// Matching is keyword-based over the lowercased role, using whole-word regexes so
// substrings inside longer words don't false-match ("art" won't match inside
// "Bartholomew"). CATEGORIES is ordered by precedence: the first category with a
// matching keyword wins, so more distinctive roles are listed before ambiguous
// ones (e.g. "prime minister" resolves to Politician before a bare "minister"
// could fall through to Religion). A role that matches nothing keeps its own
// label (trimmed) so no data is silently lost.

interface Category {
  label: string;
  keywords: string[];
}

// Order matters — earlier categories take precedence on overlap.
const CATEGORIES: Category[] = [
  {
    label: "Politician",
    keywords: [
      "prime minister",
      "first minister",
      "foreign minister",
      "cabinet minister",
      "government minister",
      "minister of state",
      "minister for",
      "minister of the crown",
      "politician",
      "statesman",
      "stateswoman",
      "member of parliament",
      "\\bmp\\b",
      "\\bpm\\b",
      "president",
      "vice-president",
      "chancellor",
      "diplomat",
      "ambassador",
      "consul",
      "mayor",
      "alderman",
      "councillor",
      "viceroy",
      "governor",
      "secretary of state",
      "home secretary",
      "foreign secretary",
      "premier",
      "senator",
      "congressman",
    ],
  },
  {
    label: "Royalty",
    keywords: [
      "king",
      "queen",
      "prince",
      "princess",
      "emperor",
      "empress",
      "monarch",
      "\\btsar\\b",
      "\\bczar\\b",
      "sultan",
      "maharaja",
      "maharajah",
      "\\braja\\b",
      "duke",
      "duchess",
    ],
  },
  {
    label: "Religion",
    keywords: [
      "bishop",
      "archbishop",
      "cardinal",
      "\\bpope\\b",
      "priest",
      "clergyman",
      "cleric",
      "chaplain",
      "preacher",
      "minister", // religious minister; political ones caught above
      "\\brabbi\\b",
      "\\bimam\\b",
      "missionary",
      "theologian",
      "evangelist",
      "\\bpastor\\b",
      "reverend",
      "\\bnun\\b",
      "\\bmonk\\b",
      "\\bfriar\\b",
      "\\bsaint\\b",
      "methodist",
      "quaker",
      "puritan",
      "congregationalist",
      "nonconformist",
    ],
  },
  {
    label: "Military",
    keywords: [
      "soldier",
      "general",
      "admiral",
      "field marshal",
      "marshal",
      "colonel",
      "brigadier",
      "lieutenant",
      "\\bmajor\\b",
      "commander",
      "commodore",
      "\\bofficer\\b",
      "sailor",
      "seaman",
      "airman",
      "\\bnaval\\b",
      "\\bnavy\\b",
      "\\barmy\\b",
      "\\bmilitary\\b",
      "serviceman",
      "regiment",
      "\\bvc\\b",
    ],
  },
  {
    label: "Writer",
    keywords: [
      "writer",
      "author",
      "novelist",
      "\\bpoet\\b",
      "poetess",
      "playwright",
      "dramatist",
      "essayist",
      "journalist",
      "\\beditor\\b",
      "biographer",
      "diarist",
      "satirist",
      "correspondent",
      "columnist",
      "screenwriter",
      "librettist",
      "translator",
      "critic",
    ],
  },
  {
    label: "Artist",
    keywords: [
      "painter",
      "sculptor",
      "\\bartist\\b",
      "illustrator",
      "engraver",
      "etcher",
      "cartoonist",
      "caricaturist",
      "photographer",
      "\\bpotter\\b",
      "ceramicist",
      "\\bmuralist\\b",
      "draughtsman",
    ],
  },
  {
    label: "Musician",
    keywords: [
      "composer",
      "musician",
      "\\bsinger\\b",
      "conductor",
      "pianist",
      "violinist",
      "cellist",
      "organist",
      "songwriter",
      "bandleader",
      "\\bopera\\b",
      "vocalist",
      "guitarist",
      "flautist",
      "drummer",
      "harpist",
    ],
  },
  {
    label: "Performer",
    keywords: [
      "\\bactor\\b",
      "actress",
      "performer",
      "comedian",
      "comedienne",
      "\\bdancer\\b",
      "ballerina",
      "entertainer",
      "magician",
      "impresario",
      "\\bclown\\b",
      "film director",
      "theatre director",
      "stage director",
      "film-maker",
      "filmmaker",
      "film producer",
    ],
  },
  {
    label: "Scientist",
    keywords: [
      "scientist",
      "physicist",
      "chemist",
      "biologist",
      "botanist",
      "naturalist",
      "astronomer",
      "geologist",
      "mathematician",
      "zoologist",
      "physiologist",
      "bacteriologist",
      "biochemist",
      "crystallographer",
      "meteorologist",
      "statistician",
      "geneticist",
      "\\bphysics\\b",
      "chemistry",
    ],
  },
  {
    label: "Engineer",
    keywords: ["engineer", "inventor", "\\bengineering\\b"],
  },
  {
    label: "Medicine",
    keywords: [
      "\\bdoctor\\b",
      "physician",
      "surgeon",
      "\\bnurse\\b",
      "psychiatrist",
      "psychoanalyst",
      "psychologist",
      "anatomist",
      "dentist",
      "pharmacist",
      "\\bmidwife\\b",
      "epidemiologist",
      "pathologist",
      "radiologist",
      "\\bmedical\\b",
      "\\bmedicine\\b",
      "apothecary",
    ],
  },
  {
    label: "Architect",
    keywords: ["architect", "town planner", "\\bsurveyor\\b"],
  },
  {
    label: "Academic",
    keywords: [
      "historian",
      "philosopher",
      "economist",
      "scholar",
      "academic",
      "professor",
      "lecturer",
      "linguist",
      "archaeologist",
      "egyptologist",
      "orientalist",
      "antiquary",
      "antiquarian",
      "librarian",
      "educationalist",
      "educationist",
      "educator",
      "\\bteacher\\b",
      "headmaster",
      "headmistress",
      "sociologist",
      "anthropologist",
      "geographer",
      "lexicographer",
      "\\btutor\\b",
    ],
  },
  {
    label: "Law",
    keywords: [
      "lawyer",
      "barrister",
      "solicitor",
      "\\bjudge\\b",
      "jurist",
      "magistrate",
      "advocate",
      "\\bqc\\b",
      "attorney",
    ],
  },
  {
    label: "Business",
    keywords: [
      "businessman",
      "businesswoman",
      "industrialist",
      "manufacturer",
      "merchant",
      "entrepreneur",
      "\\bbanker\\b",
      "financier",
      "\\bbrewer\\b",
      "retailer",
      "publisher",
      "\\bprinter\\b",
      "\\bdraper\\b",
      "\\bgrocer\\b",
      "hotelier",
      "restaurateur",
      "\\btrader\\b",
      "magnate",
      "tycoon",
      "\\bfounder\\b",
      "proprietor",
      "shopkeeper",
    ],
  },
  {
    label: "Sport",
    keywords: [
      "footballer",
      "cricketer",
      "\\bboxer\\b",
      "athlete",
      "sportsman",
      "sportswoman",
      "\\btennis\\b",
      "golfer",
      "\\bjockey\\b",
      "swimmer",
      "cyclist",
      "\\brower\\b",
      "racing driver",
      "wrestler",
      "footballing",
    ],
  },
  {
    label: "Explorer",
    keywords: [
      "explorer",
      "aviator",
      "aviatrix",
      "\\bpilot\\b",
      "mountaineer",
      "navigator",
      "adventurer",
      "balloonist",
      "astronaut",
      "circumnavigator",
    ],
  },
  {
    label: "Activist",
    keywords: [
      "activist",
      "reformer",
      "campaigner",
      "suffragette",
      "suffragist",
      "philanthropist",
      "abolitionist",
      "humanitarian",
      "feminist",
      "trade unionist",
      "trades unionist",
      "\\bunionist\\b",
      "pacifist",
      "\\bsocialist\\b",
      "\\bcommunist\\b",
      "benefactor",
      "\\bnurse\\b",
    ],
  },
];

// Precompile one whole-word regex per category. Keywords that already contain
// `\b` anchors are used verbatim; the rest are wrapped in word boundaries.
const COMPILED: { label: string; re: RegExp }[] = CATEGORIES.map((c) => {
  const parts = c.keywords.map((k) =>
    k.includes("\\b") ? k : `\\b${k}\\b`,
  );
  return { label: c.label, re: new RegExp(`(?:${parts.join("|")})`, "i") };
});

/**
 * Generalise a raw profession/role string to a broad category label.
 * Returns "Unknown" for null/empty input, and — for a role that matches no
 * category — the trimmed original so nothing is silently discarded.
 */
export function categoriseProfession(raw: string | null | undefined): string {
  const role = raw?.trim();
  if (!role) return "Unknown";
  for (const { label, re } of COMPILED) {
    if (re.test(role)) return label;
  }
  return role;
}

/** The broad category labels, in display precedence order. Handy for docs/tests. */
export const PROFESSION_CATEGORIES = CATEGORIES.map((c) => c.label);
